package com.preludeofme.squishmate.anim

import kotlin.math.PI
import kotlin.math.abs
import kotlin.math.cos
import kotlin.math.exp
import kotlin.math.hypot
import kotlin.math.max
import kotlin.math.min
import kotlin.math.sin
import kotlin.random.Random

/**
 * Kotlin port of `ui/pet_animator.py` — procedural animation state machine
 * for the pet. Pure Kotlin (no Android imports), same as the Python
 * original being pure-Python/Qt-free, so it can be unit-tested on the plain
 * JVM (see `src/test/java/.../anim/PetAnimatorGoldenTest.kt`, which replays
 * a scripted sequence and diffs against a fixture generated by
 * `scripts/generate_animator_golden.py` in the desktop repo).
 *
 * Every deterministic pose-shaping formula (sin/cos/exp of elapsed
 * state-time) is a straight line-for-line port and MUST stay numerically
 * identical to the Python original — that's what the golden test verifies.
 * Anything that reads from `Random` (natural idle scheduling, wander/
 * surprise-flee target picking, blinking) is intentionally NOT expected to
 * match Python's RNG output bit-for-bit (Python's Mersenne Twister and
 * Kotlin's `Random` are different algorithms) — the golden fixture avoids
 * exercising those paths entirely (see the generator script's docstring).
 */
enum class PetState {
    IDLE, HOP, WAVE, SLEEP, SURPRISED, DRAGGED, YAWN, STRETCH, DANCE,
    SOMERSAULT, EAT, GIGGLE,
}

val ACTION_STATES = listOf(
    PetState.YAWN, PetState.STRETCH, PetState.DANCE, PetState.SOMERSAULT, PetState.EAT,
)

data class Pose(
    var t: Double = 0.0,
    var scaleX: Double = 1.0,
    var scaleY: Double = 1.0,
    var offsetY: Double = 0.0,
    var antennaSway: Double = 0.0,
    var armL: Double = 0.0,
    var armR: Double = 0.0,
    var eyeOpen: Double = 1.0,
    var eyeScale: Double = 1.0,
    var pupilDx: Double = 0.0,
    var pupilDy: Double = 0.0,
    var mouth: Double = 0.5,
    var mouthOpen: Double = 0.0,
    var blush: Double = 0.6,
    var brow: Double = 0.0,
    var bodyRotation: Double = 0.0,
    var foodVisual: Double = 0.0,
    var sleeping: Boolean = false,
)

private fun clamp(v: Double, lo: Double, hi: Double): Double = max(lo, min(hi, v))

class PetAnimator(
    val winW: Double,
    val winH: Double,
    var hopRange: Pair<Double, Double> = Pair(8.0, 16.0),
    var waveRange: Pair<Double, Double> = Pair(25.0, 50.0),
    var wanderRange: Pair<Double, Double> = Pair(25.0, 60.0),
    var sleepAfter: Double = SLEEP_AFTER_DEFAULT,
    var actionRange: Pair<Double, Double> = Pair(45.0, 110.0),
    private val random: Random = Random.Default,
) {
    companion object {
        const val WANDER_SPEED = 90.0
        const val HOP_HEIGHT = 26.0
        const val SLEEP_AFTER_DEFAULT = 120.0
    }

    var state: PetState = PetState.IDLE
        private set
    var t: Double = 0.0
        private set
    var stateTime: Double = 0.0
        private set

    var x: Double = 200.0
    var y: Double = 200.0
    var targetX: Double = x
    var targetY: Double = y
    var moving: Boolean = false
    private var vx: Double = 0.0

    private var ant: Double = 0.0
    private var antVel: Double = 0.0
    private var prevOffsetY: Double = 0.0

    var lastScreen: IntArray = intArrayOf(0, 0, 1920, 1080)

    var nextBlink: Double = 2.5
    private var blinkStart: Double = -1.0

    private var nextHop: Double = 0.0
    private var nextWave: Double = 0.0
    private var nextWander: Double = 0.0
    private var nextAction: Double = 0.0
    private var lastInteraction: Double = 0.0
    var stayStill: Boolean = false

    var expression: Emotion = Emotion.NEUTRAL
        private set
    private var exprStart: Double = 0.0
    private var exprEnd: Double = 0.0

    init {
        nextHop = sched(hopRange)
        nextWave = sched(waveRange)
        nextWander = sched(wanderRange)
        nextAction = sched(actionRange)
    }

    /** Lowercase name of the current animation state — matches Python's
     * `current_state` property (used for e.g. bridging into
     * `windowAnimator.currentState == "sleep"` style checks). */
    val currentState: String get() = state.name.lowercase()

    // ----------------------------------------------------------- transitions
    private fun sched(range: Pair<Double, Double>): Double {
        // Kotlin's Random.nextDouble(from, until) requires from < until
        // (unlike Python's random.uniform, which tolerates a==b) — golden
        // tests deliberately pass equal "effectively infinite" bounds (see
        // scripts/generate_animator_golden.py) to disable auto-scheduling
        // entirely, so fall back to a fixed offset rather than crashing.
        return if (range.second > range.first) t + random.nextDouble(range.first, range.second)
        else t + range.first
    }

    fun setFrequencies(
        hopRange: Pair<Double, Double>? = null,
        waveRange: Pair<Double, Double>? = null,
        wanderRange: Pair<Double, Double>? = null,
        sleepAfter: Double? = null,
        actionRange: Pair<Double, Double>? = null,
    ) {
        hopRange?.let { this.hopRange = it }
        waveRange?.let { this.waveRange = it }
        wanderRange?.let { this.wanderRange = it }
        sleepAfter?.let { this.sleepAfter = it }
        actionRange?.let { this.actionRange = it }
    }

    private fun enter(newState: PetState) {
        state = newState
        stateTime = 0.0
    }

    fun setPos(nx: Double, ny: Double) {
        x = nx
        y = ny
        targetX = x
        targetY = y
    }

    fun startDrag() {
        wake()
        moving = false
        enter(PetState.DRAGGED)
    }

    fun endDrag() {
        targetX = x
        targetY = y
        enter(PetState.IDLE)
        nextWander = sched(wanderRange)
    }

    /** Click reaction: startled pop, then scoot to the opposite side.
     * `screen` = (x, y, w, h). */
    fun surpriseAndFlee(screen: IntArray) {
        wake()
        enter(PetState.SURPRISED)
        val (sx, sy, sw, sh) = screen
        val maxX = sx + max(0, sw - winW.toInt())
        val maxY = sy + max(60, sh - winH.toInt())
        val cx = x + winW / 2
        val cy = y + winH / 2
        var xLo: Double; var xHi: Double
        if (cx < sx + sw / 2.0) {
            xLo = (sx + (sw * 0.60).toInt()).toDouble(); xHi = maxX.toDouble()
        } else {
            xLo = sx.toDouble(); xHi = (sx + (sw * 0.40).toInt()).toDouble()
        }
        var yLo: Double; var yHi: Double
        if (cy < sy + sh / 2.0) {
            yLo = (sy + (sh * 0.55).toInt()).toDouble(); yHi = maxY.toDouble()
        } else {
            yLo = (sy + 60).toDouble(); yHi = (sy + (sh * 0.40).toInt()).toDouble()
        }
        val (xLoC, xHiC) = listOf(clamp(xLo, sx.toDouble(), maxX.toDouble()), clamp(xHi, sx.toDouble(), maxX.toDouble())).sorted()
        val (yLoC, yHiC) = listOf(clamp(yLo, sy.toDouble(), maxY.toDouble()), clamp(yHi, sy.toDouble(), maxY.toDouble())).sorted()
        targetX = random.nextDouble(xLoC, if (xHiC > xLoC) xHiC else xLoC + 0.0001)
        targetY = random.nextDouble(yLoC, if (yHiC > yLoC) yHiC else yLoC + 0.0001)
    }

    /** Overlay a temporary facial expression on top of whatever [state] is
     * already doing. Blended in/out over [update] calls — ignored while
     * SLEEP/DRAGGED/SURPRISED already own the face. */
    fun setExpression(emotion: Emotion, duration: Double = DEFAULT_EXPRESSION_DURATION) {
        expression = emotion
        exprStart = t
        exprEnd = t + max(0.5, duration)
    }

    // `force=true` bypasses the normal state guard — mirrors pet_debug.py's
    // DebugDialog letting a tester spam triggers without waiting for IDLE.
    fun triggerHop(force: Boolean = false) {
        if (force || state == PetState.IDLE || state == PetState.WAVE) enter(PetState.HOP)
    }

    fun triggerWave(force: Boolean = false) {
        if (force || state == PetState.IDLE) enter(PetState.WAVE)
    }

    fun triggerYawn(force: Boolean = false) {
        if (force || state == PetState.IDLE) enter(PetState.YAWN)
    }

    fun triggerStretch(force: Boolean = false) {
        if (force || state == PetState.IDLE) enter(PetState.STRETCH)
    }

    fun triggerDance(force: Boolean = false) {
        if (force || state == PetState.IDLE) enter(PetState.DANCE)
    }

    fun triggerSomersault(force: Boolean = false) {
        if (force || state == PetState.IDLE) enter(PetState.SOMERSAULT)
    }

    fun triggerEat(force: Boolean = false) {
        if (force || state == PetState.IDLE) enter(PetState.EAT)
    }

    fun triggerSleep(force: Boolean = false) {
        if (force || state == PetState.IDLE) enter(PetState.SLEEP)
    }

    /** Tickled reaction — fired when the user wiggles the cursor over the
     * pet. */
    fun triggerGiggle(force: Boolean = false) {
        if (force || state == PetState.IDLE) enter(PetState.GIGGLE)
    }

    fun triggerWander(force: Boolean = false) {
        if (force || state == PetState.IDLE) {
            val (sx, sy, sw, sh) = lastScreen
            targetX = random.nextDouble(sx.toDouble(), sx + max(0, sw - winW.toInt()) + 0.0001)
            targetY = random.nextDouble(sy + 60.0, sy + max(60, sh - winH.toInt()) + 0.0001)
            moving = true
            if (state != PetState.IDLE) enter(PetState.IDLE)
        }
    }

    fun triggerScreenTraversal(force: Boolean = false) {
        if (force || state == PetState.IDLE) {
            val (sx, sy, sw, sh) = lastScreen
            val cx = x + winW / 2
            targetX = if (cx < sx + sw / 2.0) {
                random.nextDouble(sx + sw * 0.6, (sx + max(0, sw - winW.toInt())).toDouble())
            } else {
                random.nextDouble(sx.toDouble(), sx + sw * 0.4)
            }
            targetY = random.nextDouble(sy + 60.0, sy + max(60, sh - winH.toInt()) + 0.0001)
            moving = true
            if (state != PetState.IDLE) enter(PetState.IDLE)
        }
    }

    fun triggerWobble(force: Boolean = false) = triggerHop(force)
    fun triggerBounce(force: Boolean = false) = triggerHop(force)
    fun triggerExcited(force: Boolean = false) = triggerDance(force)
    fun triggerSettle(force: Boolean = false) = triggerStretch(force)
    fun triggerRest(force: Boolean = false) = triggerYawn(force)
    fun triggerPeek(force: Boolean = false) = triggerWave(force)

    /** Something happened (bubble shown, user interacted) — stay awake. */
    fun notifyActivity() {
        lastInteraction = t
        if (state == PetState.SLEEP) wake()
    }

    fun wake() {
        lastInteraction = t
        if (state == PetState.SLEEP) enter(PetState.SURPRISED)
    }

    /** Dispatches an engine action string (e.g. from `core/bridge.py`'s
     * `PetBridge.Snapshot.action`) to the matching trigger — mirrors
     * desktop's `desktop_pet.py` `_tick_engine`'s
     * `trigger_method = f"trigger_{action}"` dispatch. Unknown/"idle"
     * actions are a no-op. */
    fun triggerAction(action: String, force: Boolean = false) {
        when (action) {
            "wobble" -> triggerWobble(force)
            "peek" -> triggerPeek(force)
            "wave" -> triggerWave(force)
            "hop" -> triggerHop(force)
            "bounce" -> triggerBounce(force)
            "screen_traversal" -> triggerScreenTraversal(force)
            "excited" -> triggerExcited(force)
            "yawn" -> triggerYawn(force)
            "stretch" -> triggerSettle(force)
            "dance" -> triggerDance(force)
            "somersault" -> triggerSomersault(force)
            "eat" -> triggerEat(force)
            "sleep" -> triggerSleep(force)
            "settle" -> triggerSettle(force)
            "rest" -> triggerRest(force)
            "wander" -> triggerWander(force)
            else -> Unit
        }
    }

    // ----------------------------------------------------------------- update
    /** Advance the simulation. `dt` seconds since last frame, `cursor` =
     * global cursor/touch position, `screen` = (x, y, w, h) available
     * screen geometry. Returns a [Pose] for the renderer. */
    fun update(dtIn: Double, cursor: DoubleArray, screen: IntArray): Pose {
        val dt = clamp(dtIn, 0.0, 0.1)
        t += dt
        stateTime += dt
        lastScreen = screen

        val pose = Pose(t = t)

        updateBehavior(screen)
        updateMovement(dt)
        updateStatePose(pose)
        updateAntenna(dt, pose)
        updateEyes(cursor, pose)
        applyExpression(pose)
        return pose
    }

    // -------------------------------------------------------------- expression
    private fun applyExpression(pose: Pose) {
        if (expression == Emotion.NEUTRAL) return
        if (state == PetState.SLEEP || state == PetState.DRAGGED || state == PetState.SURPRISED) return
        val remaining = exprEnd - t
        if (remaining <= 0) {
            expression = Emotion.NEUTRAL
            return
        }
        val elapsed = t - exprStart
        val fadeIn = clamp(elapsed / 0.3, 0.0, 1.0)
        val fadeOut = clamp(remaining / 0.8, 0.0, 1.0)
        val k = min(fadeIn, fadeOut)
        if (k <= 0.0) return
        val params = EMOTION_POSE[expression] ?: return
        params.mouth?.let { pose.mouth = pose.mouth * (1 - k) + it * k }
        params.mouthOpen?.let { pose.mouthOpen = max(pose.mouthOpen, it * k) }
        params.blush?.let { pose.blush = clamp(pose.blush + it * k, 0.0, 1.0) }
        params.eyeScale?.let { pose.eyeScale = pose.eyeScale * (1 - k) + it * k }
        if (params.eyeOpenCap != null && pose.eyeOpen > params.eyeOpenCap) {
            pose.eyeOpen = pose.eyeOpen * (1 - k) + params.eyeOpenCap * k
        }
        pose.brow = params.brow * k
        params.tremble?.let { pose.antennaSway += sin(t * 42.0) * it * k }
    }

    // -------------------------------------------------------------- behaviors
    private fun updateBehavior(screen: IntArray) {
        if (state != PetState.IDLE) return
        if (t - lastInteraction > sleepAfter) {
            moving = false
            enter(PetState.SLEEP)
            return
        }
        if (t >= nextHop) {
            nextHop = sched(hopRange)
            enter(PetState.HOP)
            return
        }
        if (t >= nextWave && !moving) {
            nextWave = sched(waveRange)
            enter(PetState.WAVE)
            return
        }
        if (!moving && t >= nextAction) {
            nextAction = sched(actionRange)
            enter(ACTION_STATES[random.nextInt(ACTION_STATES.size)])
            return
        }
        if (!stayStill && !moving && t >= nextWander) {
            val (sx, sy, sw, sh) = screen
            targetX = random.nextDouble(sx.toDouble(), sx + max(0, sw - winW.toInt()) + 0.0001)
            targetY = random.nextDouble(sy + 60.0, sy + max(60, sh - winH.toInt()) + 0.0001)
            moving = true
        }
    }

    private fun updateMovement(dt: Double) {
        if (state == PetState.DRAGGED || state == PetState.SLEEP || state == PetState.WAVE ||
            state == PetState.HOP || state == PetState.GIGGLE || state in ACTION_STATES
        ) {
            vx *= max(0.0, 1.0 - dt * 6)
            return
        }
        val dx = targetX - x
        val dy = targetY - y
        val dist = hypot(dx, dy)
        if (dist < 2.0) {
            if (moving) {
                moving = false
                nextWander = sched(wanderRange)
            }
            vx *= max(0.0, 1.0 - dt * 6)
            return
        }
        val speed = clamp(dist * 1.2, 25.0, WANDER_SPEED)
        val step = min(dist, speed * dt)
        val nx = x + dx / dist * step
        vx = if (dt > 0) (nx - x) / dt else 0.0
        x = nx
        y += dy / dist * step
        moving = true
    }

    // ------------------------------------------------------------- state pose
    private fun updateStatePose(pose: Pose) {
        val st = stateTime

        val breathX = 1.0 + sin(t * 2.0) * 0.02
        val breathY = 1.0 - sin(t * 2.0) * 0.025

        pose.armL = sin(t * 2.2) * 2.5
        pose.armR = -sin(t * 2.2) * 2.5

        when (state) {
            PetState.IDLE -> {
                pose.scaleX = breathX; pose.scaleY = breathY
                pose.mouth = 0.55
                if (moving) pose.offsetY = -abs(sin(t * 7.0)) * 3.0
            }
            PetState.HOP -> {
                poseHop(st, pose)
                if (stateTime > 1.24) enter(PetState.IDLE)
            }
            PetState.WAVE -> {
                pose.scaleX = breathX; pose.scaleY = breathY
                pose.armR = -14.0 + sin(st * 11.0) * 6.0
                pose.mouth = 0.9
                pose.blush = 0.9
                if (st > 1.8) enter(PetState.IDLE)
            }
            PetState.SLEEP -> {
                pose.scaleX = 1.0 + sin(t * 1.1) * 0.035
                pose.scaleY = 1.0 - sin(t * 1.1) * 0.04
                pose.eyeOpen = 0.0
                pose.mouth = 0.15
                pose.sleeping = true
                pose.armL = 2.0; pose.armR = 2.0
            }
            PetState.SURPRISED -> {
                val k = exp(-st * 3.0)
                pose.scaleX = 1.0 - 0.10 * k
                pose.scaleY = 1.0 + 0.14 * k
                pose.offsetY = -8.0 * sin(clamp(st / 0.35, 0.0, 1.0) * PI)
                pose.eyeScale = 1.0 + 0.35 * k
                pose.mouthOpen = k
                pose.armL = -8.0 * k; pose.armR = -8.0 * k
                if (st > 0.9) enter(PetState.IDLE)
            }
            PetState.DRAGGED -> {
                pose.scaleX = 0.94
                pose.scaleY = 1.08 + sin(t * 9.0) * 0.02
                pose.eyeScale = 1.25
                pose.mouthOpen = 0.7
                pose.armL = -9.0; pose.armR = -9.0
            }
            PetState.YAWN -> {
                poseYawn(st, pose)
                if (st > 1.5) enter(PetState.IDLE)
            }
            PetState.STRETCH -> {
                poseStretch(st, pose)
                if (st > 1.85) enter(PetState.IDLE)
            }
            PetState.DANCE -> {
                poseDance(st, pose)
                if (st > 2.6) enter(PetState.IDLE)
            }
            PetState.SOMERSAULT -> {
                poseSomersault(st, pose)
                if (st > 1.15) enter(PetState.IDLE)
            }
            PetState.EAT -> {
                poseEat(st, pose)
                if (st > 1.9) enter(PetState.IDLE)
            }
            PetState.GIGGLE -> {
                poseGiggle(st, pose)
                if (st > 1.0) enter(PetState.IDLE)
            }
        }
    }

    private fun poseYawn(st: Double, pose: Pose) {
        val t1 = 0.45; val t2 = 0.55; val t3 = 0.45
        pose.mouthOpen = when {
            st < t1 -> (st / t1) * 0.9
            st < t1 + t2 -> 0.9
            st < t1 + t2 + t3 -> 0.9 * (1.0 - (st - t1 - t2) / t3)
            else -> 0.0
        }
        pose.eyeOpen = clamp(1.0 - pose.mouthOpen * 0.7, 0.2, 1.0)
        val stretch = min(1.0, st / (t1 + t2))
        pose.armL = -6.0 * stretch; pose.armR = -6.0 * stretch
        pose.scaleY = 1.0 + 0.05 * pose.mouthOpen
        pose.scaleX = 1.0 - 0.03 * pose.mouthOpen
    }

    private fun poseStretch(st: Double, pose: Pose) {
        val t1 = 0.5; val t2 = 0.7; val t3 = 0.5
        val p = when {
            st < t1 -> st / t1
            st < t1 + t2 -> 1.0
            st < t1 + t2 + t3 -> 1.0 - (st - t1 - t2) / t3
            else -> 0.0
        }
        pose.armL = -22.0 * p; pose.armR = -22.0 * p
        pose.scaleY = 1.0 + 0.12 * p
        pose.scaleX = 1.0 - 0.08 * p
        pose.mouth = 0.7
        pose.blush = 0.7
    }

    private fun poseDance(st: Double, pose: Pose) {
        val beat = st * 8.0
        pose.scaleX = 1.0 + sin(beat) * 0.06
        pose.scaleY = 1.0 - sin(beat) * 0.05
        pose.offsetY = -abs(sin(beat)) * 6.0
        pose.armL = sin(beat) * 14.0
        pose.armR = -sin(beat + PI) * 14.0
        pose.bodyRotation = sin(st * 4.0) * 8.0
        pose.mouth = 0.9
        pose.blush = 0.9
    }

    private fun poseSomersault(st: Double, pose: Pose) {
        val tDur = 1.0
        val p = clamp(st / tDur, 0.0, 1.0)
        pose.bodyRotation = 360.0 * p
        pose.offsetY = -HOP_HEIGHT * 1.4 * sin(PI * p)
        pose.scaleX = 1.0 - 0.10 * sin(PI * p)
        pose.scaleY = 1.0 + 0.10 * sin(PI * p)
        pose.armL = -10.0 * sin(PI * p); pose.armR = -10.0 * sin(PI * p)
    }

    private fun poseEat(st: Double, pose: Pose) {
        val tDur = 1.9
        val chew = (sin(st * 10.0) + 1.0) / 2.0
        pose.mouthOpen = 0.15 + chew * 0.35
        pose.foodVisual = max(0.0, 1.0 - st / tDur)
        pose.mouth = 0.6
        pose.blush = 0.8
    }

    private fun poseGiggle(st: Double, pose: Pose) {
        val beat = st * 15.0
        val decay = exp(-st * 2.2)
        pose.scaleX = 1.0 + sin(beat) * 0.09 * decay
        pose.scaleY = 1.0 - sin(beat) * 0.07 * decay
        pose.offsetY = -abs(sin(beat * 0.5)) * 5.0 * decay
        pose.armL = sin(beat) * 10.0 * decay
        pose.armR = -sin(beat + PI) * 10.0 * decay
        pose.mouth = 1.0
        pose.mouthOpen = 0.3 * decay
        pose.blush = 1.0
        pose.eyeOpen = clamp(1.0 - 0.3 * decay, 0.6, 1.0)
    }

    private fun poseHop(st: Double, pose: Pose) {
        val t1 = 0.14; val t2 = 0.46; val t3 = 0.14
        when {
            st < t1 -> {
                val p = st / t1
                pose.scaleX = 1.0 + 0.16 * p
                pose.scaleY = 1.0 - 0.16 * p
            }
            st < t1 + t2 -> {
                val p = (st - t1) / t2
                pose.offsetY = -HOP_HEIGHT * sin(PI * p)
                val speed = abs(cos(PI * p))
                pose.scaleX = 1.0 - 0.12 * speed
                pose.scaleY = 1.0 + 0.15 * speed
            }
            st < t1 + t2 + t3 -> {
                val p = (st - t1 - t2) / t3
                val k = 1.0 - p * 0.35
                pose.scaleX = 1.0 + 0.18 * k
                pose.scaleY = 1.0 - 0.18 * k
            }
            else -> {
                val p = st - t1 - t2 - t3
                val wob = sin(p * 18.0) * 0.08 * exp(-p * 4.0)
                pose.scaleX = 1.0 + wob
                pose.scaleY = 1.0 - wob
            }
        }
        pose.mouth = 0.8
    }

    // ---------------------------------------------------------------- antenna
    private fun updateAntenna(dt: Double, pose: Pose) {
        val bodyVy = if (dt > 0) (pose.offsetY - prevOffsetY) / dt else 0.0
        prevOffsetY = pose.offsetY
        val drive = clamp(-vx * 0.06 - bodyVy * 0.05, -12.0, 12.0)
        antVel += ((drive - ant) * 40.0 - antVel * 5.0) * dt
        ant += antVel * dt
        val idleSway = sin(t * 3.0) * 3.5
        pose.antennaSway = idleSway + clamp(ant, -14.0, 14.0)
    }

    // ------------------------------------------------------------------- eyes
    private fun updateEyes(cursor: DoubleArray, pose: Pose) {
        if (state == PetState.SLEEP) return
        if (blinkStart < 0 && t >= nextBlink) {
            blinkStart = t
        }
        if (blinkStart >= 0) {
            val p = (t - blinkStart) / 0.24
            if (p >= 1.0) {
                blinkStart = -1.0
                nextBlink = sched(Pair(2.5, 6.0))
            } else {
                pose.eyeOpen = abs(p * 2.0 - 1.0)
            }
        }
        if (state == PetState.SURPRISED || state == PetState.DRAGGED) {
            pose.eyeOpen = 1.0
        }
        val cx = x + winW / 2
        val cy = y + winH / 2
        pose.pupilDx = clamp((cursor[0] - cx) / 300.0, -1.0, 1.0)
        pose.pupilDy = clamp((cursor[1] - cy) / 300.0, -1.0, 1.0)
        if (moving) {
            val direction = if (targetX > x) 1 else -1
            pose.pupilDx = clamp(pose.pupilDx + direction * 0.4, -1.0, 1.0)
        }
    }
}
